# Generated by Django 4.1.7 on 2023-03-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='stripe_id',
        ),
    ]
