# Generated by Django 4.1.7 on 2023-03-09 01:27

import django.core.validators
from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_transcript_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='file',
            field=models.FileField(upload_to=v1.models.generate_filename, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])]),
        ),
    ]
