# Generated by Django 4.1.7 on 2023-03-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_alter_transcript_result_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='transcription_method',
            field=models.CharField(blank=True, default='sm-en', max_length=5),
        ),
    ]
