# Generated by Django 4.1.7 on 2023-03-15 01:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import v1.models
import v1.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0008_transcript_transcription_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='file',
            field=models.FileField(upload_to=v1.models.generate_filename, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])]),
        ),
    ]
