# Generated by Django 4.1.7 on 2023-03-15 01:31

import django.core.validators
from django.db import migrations, models
import v1.models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_alter_transcript_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='file',
            field=models.FileField(upload_to=v1.models.generate_filename, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'm4a'])]),
        ),
    ]
